#!/usr/bin/env python3.13
"""
Generate pages/pearl-earring/pattern-data.js from pattern.json.

The PDF stores the chart with ridges along the horizontal axis and
stitches along the vertical axis.  We transpose here so the viewer
shows stitches running left→right and ridges running bottom→top,
which is the natural knitting-chart orientation.

Row model (from the PDF):
  Every ridge = 2 physical rows:
    Row 1 – Right Side (RS): knit the entire row, no chart needed.
    Row 2 – Wrong Side (WS): follow the chart.
  The viewer chart represents WS rows.  Return toggles between them.

Usage:
  python3 generate_viewer.py
  (Re-run whenever pattern.json changes.)
"""

import json
import os

JSON_PATH = os.path.join(os.path.dirname(__file__), "pattern.json")
OUTPUT    = os.path.join(os.path.dirname(__file__), "pages", "pearl-earring", "pattern-data.js")

with open(JSON_PATH) as f:
    raw = json.load(f)

# ── Transpose + orient ──────────────────────────────────────────────────────
orig       = raw["grid"]
NROWS_ORIG = raw["rows"]   # 232 stitches in the original
NCOLS_ORIG = raw["cols"]   # 183 ridges  in the original

NROWS_NEW = NCOLS_ORIG   # 183  — one display-row per ridge
NCOLS_NEW = NROWS_ORIG   # 232  — one display-col per stitch

new_grid = [
    [orig[NROWS_ORIG - 1 - c][r] for c in range(NCOLS_NEW)]
    for r in range(NROWS_NEW)
]

STITCH_AT_COL0 = 1
RIDGE_AT_ROW0  = NROWS_NEW

data = {
    "title":          raw["title"],
    "rows":           NROWS_NEW,
    "cols":           NCOLS_NEW,
    "stitch_at_col0": STITCH_AT_COL0,
    "ridge_at_row0":  RIDGE_AT_ROW0,
    "grid":           new_grid,
}
data_json = json.dumps(data, separators=(",", ":"))

os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
with open(OUTPUT, "w") as f:
    f.write(f"// Auto-generated by generate_viewer.py — do not edit by hand.\n")
    f.write(f"window.PearlEarringPattern = {data_json};\n")

size_kb = os.path.getsize(OUTPUT) / 1024
print(f"Generated {OUTPUT}  ({size_kb:.1f} KB)")
