// ─── Pearl Earring chart page ────────────────────────────────────────────────
// Depends on window.PearlEarringPattern (generated by generate_viewer.py).

(function () {

// ── Page toolbar HTML ────────────────────────────────────────────────────────
const TOOLBAR_HTML = `
<div id="page-toolbar">
  <h1 id="chart-title">Knitting Chart</h1>
  <div class="divider"></div>

  <button class="btn" id="btn-next">&#x2191; Next</button>
  <span id="ridge-badge">Ridge &#x2014; / &#x2014;</span>
  <button class="btn" id="btn-prev">&#x2193; Prev</button>

  <div class="divider"></div>

  <span class="ctrl-label">Go to ridge <input type="number" id="goto-input" min="1" value="1"></span>

  <div class="divider"></div>

  <span id="row-type-badge">Wrong Side Row</span>
  <span id="stitch-badge">St.&nbsp;1</span>

  <div class="divider"></div>

  <span class="ctrl-label">
    Zoom
    <div class="zoom-group">
      <button class="btn small" id="btn-zoom-out">&#x2212;</button>
      <input type="range" id="zoom-slider" min="1" max="40" value="20" step="1">
      <button class="btn small" id="btn-zoom-in">+</button>
    </div>
    <span id="zoom-label">20px</span>
  </span>

  <div class="divider"></div>

  <span class="ctrl-label">
    Stitch guides every
    <input type="number" id="stitch-interval" min="1" max="200" value="10" style="width:44px">
  </span>
  <span class="ctrl-label">
    Ridge guides every
    <input type="number" id="ridge-interval" min="1" max="200" value="10" style="width:44px">
  </span>
</div>`;

// ── Page body HTML ───────────────────────────────────────────────────────────
const BODY_HTML = `
<div id="scroll-wrap">
  <canvas id="col-header"></canvas>
  <canvas id="grid-canvas"></canvas>
</div>

<div id="rs-overlay">
  <div id="rs-overlay-ridgenum">Ridge <span id="rs-ridge-num">&#x2014;</span></div>
  <div id="rs-overlay-title">Right Side Row</div>
  <div id="rs-overlay-sub">Knit the entire row</div>
  <div id="rs-overlay-hint">Press Return when done to see the chart &#x2192;</div>
</div>`;

// ── Page state ───────────────────────────────────────────────────────────────
const PATTERN        = window.PearlEarringPattern;
const NROWS          = PATTERN.rows;
const NCOLS          = PATTERN.cols;
const GRID           = PATTERN.grid;
const STITCH_AT_COL0 = PATTERN.stitch_at_col0;
const RIDGE_AT_ROW0  = PATTERN.ridge_at_row0;

function stitchNum(col) { return STITCH_AT_COL0 + col; }
function ridgeNum(row)  { return RIDGE_AT_ROW0  - row; }
function rowForRidge(r) { return RIDGE_AT_ROW0  - r;   }

let activeRidge    = 1;
let activeStitch   = 1;
let isRightSideRow = false;
let stitchInterv   = 10;
let ridgeInterv    = 10;
let cellPx         = 20;

let pipWindow  = null;
let pipOffset  = 0;
let pipCanvas  = null;
let pipCtx     = null;
const PIP_CS   = 16;
const PIP_COLS = 30;
const PIP_ROWS = 5;
const PIP_LW   = 38;
const PIP_LH   = 18;

const MARKER_COLORS = [
  { name: "none",   solid: "rgba(120,120,120,0.4)", guide: "rgba(120,120,120,0.4)" },
  { name: "red",    solid: "#e05050",               guide: "rgba(210,60,60,0.75)"  },
  { name: "green",  solid: "#50b050",               guide: "rgba(50,160,50,0.75)"  },
  { name: "blue",   solid: "#4080e0",               guide: "rgba(50,100,220,0.75)" },
  { name: "yellow", solid: "#d0a020",               guide: "rgba(200,160,30,0.75)" },
  { name: "purple", solid: "#9050c0",               guide: "rgba(130,60,190,0.75)" },
];
const DEFAULT_MARKER = MARKER_COLORS[1];
const stitchGuide = {};
function guideEntry(sn) { return stitchGuide[sn] || DEFAULT_MARKER; }

const CELL_COLOR  = ["#ffffff", "#aaaaaa", "#2e2e2e"];
const RIDGE_GUIDE = "rgba(210,60,60,0.75)";
const CELL_LINE   = "rgba(0,0,0,0.30)";
const HL_FILL     = "rgba(245,200,66,0.20)";
const HL_STROKE   = "rgba(245,200,66,0.90)";
const ST_HL_FILL  = "rgba(80,200,255,0.13)";
const ST_HL_STROKE= "rgba(80,200,255,0.70)";
const LBL_BG_NORM = "rgba(28,28,28,0.85)";
const LBL_BG_ACT  = "rgba(55,45,0,0.95)";
const LBL_FG_NORM = "#666";
const LBL_FG_ACT  = "#f5c842";
const HDR_BG      = "#1a2332";

const MIN_RIDGE = 1;
const MAX_RIDGE = RIDGE_AT_ROW0;

// ── localStorage ─────────────────────────────────────────────────────────────
const LS_STATE        = "knitting_pearl_earring_state";
const LS_HISTORY      = "knitting_pearl_earring_history";
const LS_STITCH_GUIDE = "knitting_pearl_earring_stitch_guide";
const MAX_HIST        = 500;

function loadState() {
  try { return JSON.parse(localStorage.getItem(LS_STATE)); } catch { return null; }
}
function saveState() {
  localStorage.setItem(LS_STATE, JSON.stringify({
    ridge: activeRidge, stitch: activeStitch, isRightSide: isRightSideRow,
  }));
}
function loadHistory() {
  try { return JSON.parse(localStorage.getItem(LS_HISTORY)) || []; } catch { return []; }
}
function saveHistory(hist) {
  localStorage.setItem(LS_HISTORY, JSON.stringify(hist));
}
function loadStitchGuide() {
  try {
    const saved = JSON.parse(localStorage.getItem(LS_STITCH_GUIDE));
    if (saved) Object.entries(saved).forEach(([k, v]) => {
      const mc = MARKER_COLORS.find(c => c.name === v);
      if (mc) stitchGuide[+k] = mc;
    });
  } catch { /* ignore */ }
}
function saveStitchGuide() {
  const out = {};
  Object.entries(stitchGuide).forEach(([k, v]) => { out[k] = v.name; });
  localStorage.setItem(LS_STITCH_GUIDE, JSON.stringify(out));
}

// ── History auto-save ────────────────────────────────────────────────────────
let histTimer   = null;
let lastHistKey = null;
let _shellAPI   = null;

function scheduleHistEntry() {
  clearTimeout(histTimer);
  histTimer = setTimeout(() => {
    const key = `${activeRidge}:${isRightSideRow ? 1 : 0}`;
    if (key === lastHistKey) return;
    lastHistKey = key;
    const hist = loadHistory();
    hist.unshift({ ridge: activeRidge, stitch: activeStitch, isRightSide: isRightSideRow, ts: Date.now() });
    if (hist.length > MAX_HIST) hist.length = MAX_HIST;
    saveHistory(hist);
    if (_shellAPI) { _shellAPI.updateHistBadge(); _shellAPI.refreshHistory(); }
  }, 1500);
}

// ── Canvas drawing ────────────────────────────────────────────────────────────
let colHeaderCanvas, chCtx, gridCanvas, gCtx;
let ROW_LABEL_W = 0, COL_LABEL_H = 0;

function computeDims() {
  const fs = Math.max(9, Math.min(cellPx, 14));
  ROW_LABEL_W = fs * 3 + 12;
  COL_LABEL_H = fs + 12;
}
function totalW() { return ROW_LABEL_W + NCOLS * cellPx + 24; }
function totalH() { return NROWS * cellPx + 24; }

function drawColHeader() {
  const W = totalW(), H = COL_LABEL_H;
  colHeaderCanvas.width  = W;
  colHeaderCanvas.height = H;
  const fs = Math.max(9, Math.min(cellPx, 14));
  chCtx.fillStyle = HDR_BG;
  chCtx.fillRect(0, 0, W, H);
  chCtx.font         = `${fs}px monospace`;
  chCtx.textBaseline = "middle";
  chCtx.textAlign    = "center";
  chCtx.lineWidth    = 1;
  for (let c = 0; c < NCOLS; c++) {
    const sn     = stitchNum(c);
    if (sn % stitchInterv !== 0) continue;
    const lineX  = ROW_LABEL_W + (c + 1) * cellPx;
    const labelX = ROW_LABEL_W + c * cellPx + cellPx / 2;
    chCtx.strokeStyle = guideEntry(sn).guide;
    chCtx.beginPath(); chCtx.moveTo(lineX, 0); chCtx.lineTo(lineX, H); chCtx.stroke();
    chCtx.fillStyle = "#999";
    chCtx.fillText(String(sn), labelX, H / 2);
  }
  const stStartCol = activeStitch - STITCH_AT_COL0;
  const stEndCol   = Math.min(stStartCol + 9, NCOLS - 1);
  if (stStartCol >= 0 && stStartCol < NCOLS) {
    const ax = ROW_LABEL_W + stStartCol * cellPx;
    const aw = (stEndCol - stStartCol + 1) * cellPx;
    chCtx.fillStyle = "rgba(80,200,255,0.22)";
    chCtx.fillRect(ax, 0, aw, H);

    const dotR = Math.max(3, Math.min(Math.floor(H / 2) - 2, 5));
    if (aw >= dotR * 6 + 20) {
      const arrow  = "→";
      chCtx.font = `${fs}px sans-serif`;
      const arrowW = chCtx.measureText(arrow).width;
      const gap    = 4;
      const span   = dotR * 2 + gap + arrowW + gap + dotR * 2;
      const cx = ax + aw / 2, cy = H / 2;

      const leftNum    = activeStitch - 1;
      const rightNum   = Math.min(activeStitch + 9, STITCH_AT_COL0 + NCOLS - 1);
      const leftColor  = leftNum > 0 ? guideEntry(leftNum).solid : "rgba(120,120,120,0.4)";
      const rightColor = guideEntry(rightNum).solid;

      chCtx.beginPath(); chCtx.arc(cx - span/2 + dotR, cy, dotR, 0, Math.PI*2);
      chCtx.fillStyle = leftColor; chCtx.fill();

      chCtx.fillStyle = "rgba(200,200,200,0.65)";
      chCtx.textAlign = "center"; chCtx.textBaseline = "middle";
      chCtx.fillText(arrow, cx, cy);

      chCtx.beginPath(); chCtx.arc(cx + span/2 - dotR, cy, dotR, 0, Math.PI*2);
      chCtx.fillStyle = rightColor; chCtx.fill();
    }
  }
  chCtx.fillStyle = HDR_BG;
  chCtx.fillRect(0, 0, ROW_LABEL_W, H);
}

function drawGrid() {
  const W = totalW(), H = totalH(), cs = cellPx;
  const patternW = NCOLS * cs;
  const patternH = NROWS * cs;
  gridCanvas.width  = W;
  gridCanvas.height = H;

  gCtx.fillStyle = "#0d1b2a";
  gCtx.fillRect(0, 0, W, H);
  gCtx.fillStyle = "#0a1520";
  gCtx.fillRect(0, 0, ROW_LABEL_W + patternW, patternH);

  for (let r = 0; r < NROWS; r++) {
    for (let c = 0; c < NCOLS; c++) {
      gCtx.fillStyle = CELL_COLOR[GRID[r][c]] || "#f0f";
      gCtx.fillRect(ROW_LABEL_W + c * cs, r * cs, cs, cs);
    }
  }

  if (cs >= 3) {
    gCtx.beginPath();
    gCtx.strokeStyle = CELL_LINE;
    gCtx.lineWidth   = 1;
    for (let c = 0; c <= NCOLS; c++) {
      const x = ROW_LABEL_W + c * cs;
      gCtx.moveTo(x, 0); gCtx.lineTo(x, patternH);
    }
    for (let r = 0; r <= NROWS; r++) {
      const y = r * cs;
      gCtx.moveTo(ROW_LABEL_W, y); gCtx.lineTo(ROW_LABEL_W + patternW, y);
    }
    gCtx.stroke();
  }

  const guideW = Math.max(1, cs * 0.12);
  for (let c = 0; c < NCOLS; c++) {
    const sn = stitchNum(c);
    if (sn % stitchInterv !== 0) continue;
    const x = ROW_LABEL_W + (c + 1) * cs;
    gCtx.strokeStyle = guideEntry(sn).guide;
    gCtx.lineWidth   = guideW;
    gCtx.beginPath(); gCtx.moveTo(x, 0); gCtx.lineTo(x, patternH); gCtx.stroke();
  }

  gCtx.strokeStyle = RIDGE_GUIDE;
  gCtx.lineWidth   = guideW;
  gCtx.beginPath();
  for (let r = 0; r < NROWS; r++) {
    if (ridgeNum(r) % ridgeInterv === 0) {
      const y = r * cs;
      gCtx.moveTo(ROW_LABEL_W, y); gCtx.lineTo(ROW_LABEL_W + patternW, y);
    }
  }
  gCtx.stroke();

  const activeRow = rowForRidge(activeRidge);
  const ry = activeRow * cs;
  gCtx.fillStyle = HL_FILL;
  gCtx.fillRect(ROW_LABEL_W, ry, NCOLS * cs, cs);
  gCtx.strokeStyle = HL_STROKE;
  gCtx.lineWidth   = Math.max(1, cs * 0.18);
  const hw = gCtx.lineWidth / 2;
  gCtx.strokeRect(ROW_LABEL_W + hw, ry + hw, NCOLS * cs - gCtx.lineWidth, cs - gCtx.lineWidth);

  const stStartCol = activeStitch - STITCH_AT_COL0;
  const stEndCol   = Math.min(stStartCol + 9, NCOLS - 1);
  if (stStartCol >= 0 && stStartCol < NCOLS) {
    const stX = ROW_LABEL_W + stStartCol * cs;
    const stW = (stEndCol - stStartCol + 1) * cs;
    gCtx.fillStyle = ST_HL_FILL;
    gCtx.fillRect(stX, ry, stW, cs);
    gCtx.strokeStyle = ST_HL_STROKE;
    gCtx.lineWidth   = Math.max(1, cs * 0.18);
    const shw = gCtx.lineWidth / 2;
    gCtx.strokeRect(stX + shw, ry + shw, stW - gCtx.lineWidth, cs - gCtx.lineWidth);
  }

  const fs = Math.max(9, Math.min(cs, 14));
  gCtx.font         = `${fs}px monospace`;
  gCtx.textAlign    = "right";
  gCtx.textBaseline = "middle";
  const step = cs < 5 ? ridgeInterv : cs < 10 ? 5 : 1;
  for (let r = 0; r < NROWS; r++) {
    const rn       = ridgeNum(r);
    const isActive = rn === activeRidge;
    if (rn % step !== 0 && !isActive) continue;
    const y = r * cs;
    gCtx.fillStyle = isActive ? LBL_BG_ACT : LBL_BG_NORM;
    gCtx.fillRect(0, y, ROW_LABEL_W, cs);
    gCtx.fillStyle = isActive ? LBL_FG_ACT : LBL_FG_NORM;
    gCtx.fillText(String(rn), ROW_LABEL_W - 4, y + cs / 2);
  }
}

function render() {
  computeDims();
  drawColHeader();
  drawGrid();
  updateBadge();
  drawPip();
}

// ── Navigation ───────────────────────────────────────────────────────────────
function setRow(rn, isRS = isRightSideRow) {
  activeRidge    = Math.max(MIN_RIDGE, Math.min(MAX_RIDGE, rn));
  isRightSideRow = !!isRS;
  pipOffset      = 0;
  document.getElementById("goto-input").value = activeRidge;
  saveState();
  scheduleHistEntry();
  render();
  scrollToActiveRidge();
  updateBadge();
  updateSidebarCurrent();
  updateRSOverlay();
}

function setStitch(sn) {
  activeStitch = Math.max(STITCH_AT_COL0, Math.min(STITCH_AT_COL0 + NCOLS - 1, sn));
  saveState();
  render();
  scrollToActiveStitch();
}

function scrollToActiveRidge() {
  const sw  = document.getElementById("scroll-wrap");
  if (!sw) return;
  const row = rowForRidge(activeRidge);
  const y   = row * cellPx;
  const mid = sw.clientHeight / 2;
  sw.scrollTop = Math.max(0, y - mid + cellPx / 2);
}
function scrollToActiveStitch() {
  const sw = document.getElementById("scroll-wrap");
  if (!sw) return;
  const x  = ROW_LABEL_W + (activeStitch - STITCH_AT_COL0) * cellPx;
  const mid = sw.clientWidth / 2;
  sw.scrollLeft = Math.max(0, x - mid);
}

function updateBadge() {
  const ridgeBadge = document.getElementById("ridge-badge");
  const stitchBadge = document.getElementById("stitch-badge");
  const zoomLabel   = document.getElementById("zoom-label");
  if (ridgeBadge)  ridgeBadge.textContent  = `Ridge ${activeRidge} / ${MAX_RIDGE}`;
  if (stitchBadge) stitchBadge.textContent = `St.\u00a0${activeStitch}`;
  if (zoomLabel)   zoomLabel.textContent   = `${cellPx}px`;
}

function updateRSOverlay() {
  const overlay = document.getElementById("rs-overlay");
  if (!overlay) return;
  if (isRightSideRow) {
    overlay.classList.add("visible");
    const el = document.getElementById("rs-ridge-num");
    if (el) el.textContent = activeRidge;
  } else {
    overlay.classList.remove("visible");
  }
  const badge = document.getElementById("row-type-badge");
  if (badge) {
    badge.textContent = isRightSideRow ? "Right Side Row" : "Wrong Side Row";
    badge.classList.toggle("rs", isRightSideRow);
  }
}

function updateSidebarCurrent() {
  if (_shellAPI) _shellAPI.refreshHistory();
}

function setZoom(v) {
  cellPx = Math.max(1, Math.min(40, v));
  const slider = document.getElementById("zoom-slider");
  if (slider) slider.value = cellPx;
  render();
  scrollToActiveRidge();
  scrollToActiveStitch();
}

// ── Guide popup ───────────────────────────────────────────────────────────────
let popupStitch = null;

function initGuidePopup() {
  const guidePopup = document.getElementById("guide-popup");
  const swatchRow  = document.getElementById("popup-swatches");
  swatchRow.innerHTML = "";
  MARKER_COLORS.forEach(mc => {
    const sw = document.createElement("div");
    sw.className        = "swatch";
    sw.style.background = mc.solid;
    sw.dataset.color    = mc.name;
    sw.innerHTML        = `<span class="swatch-tip">${mc.name}</span>`;
    sw.addEventListener("click", e => {
      e.stopPropagation();
      if (popupStitch !== null) { stitchGuide[popupStitch] = mc; saveStitchGuide(); render(); }
      hidePopup();
    });
    swatchRow.appendChild(sw);
  });
}

function showPopup(sn, clientX, clientY) {
  popupStitch = sn;
  document.getElementById("popup-stitch-num").textContent = sn;
  const swatchRow = document.getElementById("popup-swatches");
  const guidePopup = document.getElementById("guide-popup");
  const current = guideEntry(sn).name;
  swatchRow.querySelectorAll(".swatch").forEach(sw =>
    sw.classList.toggle("active", sw.dataset.color === current));
  guidePopup.style.display = "block";
  const pw = guidePopup.offsetWidth  || 220;
  const ph = guidePopup.offsetHeight || 80;
  let x = clientX + 10, y = clientY - Math.floor(ph / 2);
  if (x + pw > window.innerWidth  - 8) x = clientX - pw - 10;
  if (y < 8)                            y = 8;
  if (y + ph > window.innerHeight - 8)  y = window.innerHeight - ph - 8;
  guidePopup.style.left = x + "px";
  guidePopup.style.top  = y + "px";
}
function hidePopup() {
  document.getElementById("guide-popup").style.display = "none";
  popupStitch = null;
}

function nearestGuide(canvasX) {
  const threshold = Math.max(5, cellPx * 0.45);
  let best = null, bestDist = Infinity;
  for (let c = 0; c < NCOLS; c++) {
    const sn = stitchNum(c);
    if (sn % stitchInterv !== 0) continue;
    const lx   = ROW_LABEL_W + (c + 1) * cellPx;
    const dist = Math.abs(canvasX - lx);
    if (dist < threshold && dist < bestDist) { bestDist = dist; best = sn; }
  }
  return best;
}

// ── Picture-in-Picture ────────────────────────────────────────────────────────
async function openPip() {
  if (pipWindow && !pipWindow.closed) {
    pipWindow.close();
    pipWindow = null; pipCanvas = null; pipCtx = null;
    document.getElementById("btn-pip").classList.remove("active");
    return;
  }
  if (document.getElementById("pip-fallback").classList.contains("visible")) {
    closeFallbackPip();
    return;
  }

  if (window.documentPictureInPicture) {
    try {
      const canvasW = PIP_LW + PIP_COLS * PIP_CS;
      const canvasH = PIP_LH + PIP_ROWS * PIP_CS;
      pipWindow = await documentPictureInPicture.requestWindow({
        width:  canvasW + 20,
        height: canvasH + 32,
      });
      const doc = pipWindow.document;

      const style = doc.createElement("style");
      style.textContent = [
        "* { box-sizing: border-box; margin: 0; padding: 0; }",
        "body { background: #0d1b2a; color: #ddd; font-family: system-ui, sans-serif;",
        "  display: flex; flex-direction: column; height: 100dvh; overflow: hidden; user-select: none; }",
        "canvas { display: block; image-rendering: pixelated; flex-shrink: 0; }",
        "#pip-scroll { display: flex; justify-content: space-between; align-items: center;",
        "  padding: 3px 6px;",
        "  background: #1a2332; border-top: 1px solid #2a3444; flex-shrink: 0; }",
        ".sbtn { cursor: pointer; padding: 2px 10px; border-radius: 4px;",
        "  background: #2a3444; color: #aaa; font-size: 0.9rem; }",
        ".sbtn:hover { background: #3a4a5a; color: #eee; }",
        "#pip-off { font-size: 0.65rem; color: #667; }",
      ].join("\n");
      doc.head.appendChild(style);

      const cv = doc.createElement("canvas");
      cv.width = canvasW; cv.height = canvasH;
      doc.body.appendChild(cv);
      pipCanvas = cv; pipCtx = cv.getContext("2d");

      const bar = doc.createElement("div");
      bar.id = "pip-scroll";
      bar.innerHTML = '<div class="sbtn" id="pip-left">◄</div>' +
                      '<span id="pip-off">centred</span>' +
                      '<div class="sbtn" id="pip-right">►</div>';
      doc.body.appendChild(bar);

      doc.getElementById("pip-left").addEventListener("click", () => {
        pipOffset = Math.max(pipOffset - 10, STITCH_AT_COL0 - activeStitch);
        drawPip();
      });
      doc.getElementById("pip-right").addEventListener("click", () => {
        pipOffset = Math.min(pipOffset + 10, STITCH_AT_COL0 + NCOLS - 1 - (activeStitch + 9));
        drawPip();
      });

      doc.addEventListener("keydown", e => {
        switch (e.key) {
          case "ArrowUp":   case "k": e.preventDefault(); setRow(activeRidge + 1); break;
          case "ArrowDown": case "j": e.preventDefault(); setRow(activeRidge - 1); break;
          case "ArrowRight": case " ": e.preventDefault(); setStitch(activeStitch + 10); break;
          case "ArrowLeft":            e.preventDefault(); setStitch(activeStitch - 10); break;
          case "Enter":
            e.preventDefault();
            if (isRightSideRow) { setRow(activeRidge, false); setStitch(STITCH_AT_COL0); }
            else                { setRow(activeRidge + 1, true); }
            break;
          case "Home":     e.preventDefault(); setRow(MIN_RIDGE); break;
          case "End":      e.preventDefault(); setRow(MAX_RIDGE);  break;
          case "PageUp":   e.preventDefault(); setRow(activeRidge + ridgeInterv); break;
          case "PageDown": e.preventDefault(); setRow(activeRidge - ridgeInterv); break;
        }
      });

      pipWindow.addEventListener("pagehide", () => {
        pipWindow = null; pipCanvas = null; pipCtx = null;
        document.getElementById("btn-pip").classList.remove("active");
      });

      document.getElementById("btn-pip").classList.add("active");
      drawPip();
      return;
    } catch { /* fall through to fallback */ }
  }
  openFallbackPip();
}

function drawPip() {
  const isFallback = !pipCtx &&
    document.getElementById("pip-fallback").classList.contains("visible");
  if (!pipCtx && !isFallback) return;

  const cv  = pipCtx ? pipCanvas : document.getElementById("pip-fallback-canvas");
  const ctx = pipCtx || cv.getContext("2d");
  const canvasW = PIP_LW + PIP_COLS * PIP_CS;
  const canvasH = PIP_LH + PIP_ROWS * PIP_CS;
  if (cv.width !== canvasW)  cv.width  = canvasW;
  if (cv.height !== canvasH) cv.height = canvasH;

  const centerStitch = activeStitch + 5 + pipOffset;
  let startStitch    = centerStitch - Math.floor(PIP_COLS / 2);
  startStitch = Math.max(STITCH_AT_COL0, startStitch);
  startStitch = Math.min(startStitch, STITCH_AT_COL0 + NCOLS - PIP_COLS);
  const startCol = startStitch - STITCH_AT_COL0;

  const activeRow = rowForRidge(activeRidge);
  let startRow    = activeRow - Math.floor(PIP_ROWS / 2);
  startRow = Math.max(0, Math.min(NROWS - PIP_ROWS, startRow));

  ctx.fillStyle = "#0a1520";
  ctx.fillRect(0, 0, canvasW, canvasH);

  ctx.fillStyle = "#1a2332";
  ctx.fillRect(PIP_LW, 0, PIP_COLS * PIP_CS, PIP_LH);
  ctx.font = "9px monospace"; ctx.textAlign = "center"; ctx.textBaseline = "middle";
  for (let i = 0; i < PIP_COLS; i++) {
    const sn = STITCH_AT_COL0 + startCol + i;
    if (sn % 10 === 0) {
      ctx.fillStyle = "#666";
      ctx.fillText(String(sn), PIP_LW + i * PIP_CS + PIP_CS / 2, PIP_LH / 2);
    }
  }

  for (let ri = 0; ri < PIP_ROWS; ri++) {
    const gr = startRow + ri;
    if (gr < 0 || gr >= NROWS) continue;
    for (let ci = 0; ci < PIP_COLS; ci++) {
      const gc = startCol + ci;
      if (gc < 0 || gc >= NCOLS) continue;
      ctx.fillStyle = CELL_COLOR[GRID[gr][gc]] || "#f0f";
      ctx.fillRect(PIP_LW + ci * PIP_CS, PIP_LH + ri * PIP_CS, PIP_CS, PIP_CS);
    }
  }

  ctx.strokeStyle = CELL_LINE; ctx.lineWidth = 0.5;
  ctx.beginPath();
  for (let ci = 0; ci <= PIP_COLS; ci++) {
    const x = PIP_LW + ci * PIP_CS;
    ctx.moveTo(x, PIP_LH); ctx.lineTo(x, PIP_LH + PIP_ROWS * PIP_CS);
  }
  for (let ri = 0; ri <= PIP_ROWS; ri++) {
    const y = PIP_LH + ri * PIP_CS;
    ctx.moveTo(PIP_LW, y); ctx.lineTo(PIP_LW + PIP_COLS * PIP_CS, y);
  }
  ctx.stroke();

  const guideW = 2;
  for (let ci = 0; ci < PIP_COLS; ci++) {
    const sn = STITCH_AT_COL0 + startCol + ci;
    if (sn % stitchInterv !== 0) continue;
    const gx = PIP_LW + (ci + 1) * PIP_CS;
    ctx.strokeStyle = guideEntry(sn).guide;
    ctx.lineWidth   = guideW;
    ctx.beginPath();
    ctx.moveTo(gx, PIP_LH);
    ctx.lineTo(gx, PIP_LH + PIP_ROWS * PIP_CS);
    ctx.stroke();
  }

  ctx.strokeStyle = RIDGE_GUIDE;
  ctx.lineWidth   = guideW;
  for (let ri = 0; ri < PIP_ROWS; ri++) {
    const gr = startRow + ri;
    if (gr < 0 || gr >= NROWS) continue;
    if (ridgeNum(gr) % ridgeInterv !== 0) continue;
    const gy = PIP_LH + ri * PIP_CS;
    ctx.beginPath();
    ctx.moveTo(PIP_LW, gy);
    ctx.lineTo(PIP_LW + PIP_COLS * PIP_CS, gy);
    ctx.stroke();
  }

  const activeRi = activeRow - startRow;
  if (activeRi >= 0 && activeRi < PIP_ROWS) {
    const ry = PIP_LH + activeRi * PIP_CS;
    ctx.fillStyle = HL_FILL;
    ctx.fillRect(PIP_LW, ry, PIP_COLS * PIP_CS, PIP_CS);
    ctx.strokeStyle = HL_STROKE; ctx.lineWidth = 2;
    ctx.strokeRect(PIP_LW + 1, ry + 1, PIP_COLS * PIP_CS - 2, PIP_CS - 2);

    const blkStart = activeStitch - STITCH_AT_COL0;
    const blkEnd   = Math.min(activeStitch + 9, STITCH_AT_COL0 + NCOLS - 1) - STITCH_AT_COL0;
    const visSCI   = Math.max(0, blkStart - startCol);
    const visECI   = Math.min(PIP_COLS - 1, blkEnd - startCol);
    if (visSCI <= visECI) {
      const stX = PIP_LW + visSCI * PIP_CS;
      const stW = (visECI - visSCI + 1) * PIP_CS;
      ctx.fillStyle = ST_HL_FILL;
      ctx.fillRect(stX, ry, stW, PIP_CS);
      ctx.strokeStyle = ST_HL_STROKE; ctx.lineWidth = 2;
      ctx.strokeRect(stX + 1, ry + 1, stW - 2, PIP_CS - 2);
    }
  }

  ctx.font = "9px monospace"; ctx.textAlign = "right"; ctx.textBaseline = "middle";
  for (let ri = 0; ri < PIP_ROWS; ri++) {
    const gr = startRow + ri;
    if (gr < 0 || gr >= NROWS) continue;
    const rn   = ridgeNum(gr);
    const isAct = rn === activeRidge;
    const y    = PIP_LH + ri * PIP_CS;
    ctx.fillStyle = isAct ? LBL_BG_ACT : "rgba(10,21,32,0.9)";
    ctx.fillRect(0, y, PIP_LW, PIP_CS);
    ctx.fillStyle = isAct ? LBL_FG_ACT : LBL_FG_NORM;
    ctx.fillText(String(rn), PIP_LW - 4, y + PIP_CS / 2);
  }

  ctx.fillStyle = "#1a2332";
  ctx.fillRect(0, 0, PIP_LW, PIP_LH);

  if (isRightSideRow) {
    const patX = PIP_LW, patY = PIP_LH;
    const patW = PIP_COLS * PIP_CS, patH = PIP_ROWS * PIP_CS;
    ctx.fillStyle = "rgba(6,6,6,0.82)";
    ctx.fillRect(patX, patY, patW, patH);
    const cx = patX + patW / 2, cy = patY + patH / 2;
    ctx.textAlign = "center"; ctx.textBaseline = "middle";
    ctx.font = "bold 13px system-ui, sans-serif";
    ctx.fillStyle = "#e8a030";
    ctx.fillText("Right Side Row", cx, cy - 8);
    ctx.font = "10px system-ui, sans-serif";
    ctx.fillStyle = "#aaa";
    ctx.fillText("Knit all — Return when done", cx, cy + 8);
  }

  if (pipWindow && !pipWindow.closed) {
    const pd = pipWindow.document;
    const oe = pd.getElementById("pip-off");
    if (oe) oe.textContent = pipOffset ? "offset " + pipOffset : "centred";
  } else if (isFallback) {
    const lbl = document.getElementById("pip-fb-label-st");
    if (lbl) lbl.textContent = "St. " + (activeStitch + pipOffset);
  }
}

function openFallbackPip() {
  const cv = document.getElementById("pip-fallback-canvas");
  cv.width  = PIP_LW + PIP_COLS * PIP_CS;
  cv.height = PIP_LH + PIP_ROWS * PIP_CS;
  document.getElementById("pip-fallback").classList.add("visible");
  document.getElementById("btn-pip").classList.add("active");
  document.getElementById("pip-fallback-close").onclick = closeFallbackPip;
  document.getElementById("pip-fb-left").onclick = () => {
    pipOffset = Math.max(pipOffset - 10, STITCH_AT_COL0 - activeStitch);
    drawPip();
  };
  document.getElementById("pip-fb-right").onclick = () => {
    pipOffset = Math.min(pipOffset + 10, STITCH_AT_COL0 + NCOLS - 1 - (activeStitch + 9));
    drawPip();
  };
  const overlay = document.getElementById("pip-fallback");
  const hdrEl   = document.getElementById("pip-fallback-header");
  hdrEl.onmousedown = e => {
    if (e.target.id === "pip-fallback-close") return;
    const rect = overlay.getBoundingClientRect();
    const dx = e.clientX - rect.left, dy = e.clientY - rect.top;
    const onMove = ev => {
      overlay.style.right = "auto"; overlay.style.bottom = "auto";
      overlay.style.left  = (ev.clientX - dx) + "px";
      overlay.style.top   = (ev.clientY - dy) + "px";
    };
    const onUp = () => {
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup",   onUp);
    };
    document.addEventListener("mousemove", onMove);
    document.addEventListener("mouseup",   onUp);
    e.preventDefault();
  };
  drawPip();
}

function closeFallbackPip() {
  document.getElementById("pip-fallback").classList.remove("visible");
  document.getElementById("btn-pip").classList.remove("active");
  pipCanvas = null; pipCtx = null;
}

// ── Event listeners (set up during mount, torn down during unmount) ───────────
const _listeners = [];
function on(el, evt, fn, opts) {
  el.addEventListener(evt, fn, opts);
  _listeners.push({ el, evt, fn, opts });
}
function removeAllListeners() {
  _listeners.forEach(({ el, evt, fn, opts }) => el.removeEventListener(evt, fn, opts));
  _listeners.length = 0;
}

function setupEvents() {
  on(document.getElementById("btn-next"), "click", () => setRow(activeRidge + 1));
  on(document.getElementById("btn-prev"), "click", () => setRow(activeRidge - 1));
  on(document.getElementById("goto-input"), "change", e =>
    setRow(parseInt(e.target.value, 10) || 1, false));

  on(document.getElementById("zoom-slider"), "input", e => setZoom(+e.target.value));
  on(document.getElementById("btn-zoom-in"),  "click", () => setZoom(cellPx + 1));
  on(document.getElementById("btn-zoom-out"), "click", () => setZoom(cellPx - 1));

  on(document.getElementById("stitch-interval"), "change", e => {
    const v = parseInt(e.target.value, 10);
    if (v >= 1) { stitchInterv = v; render(); }
  });
  on(document.getElementById("ridge-interval"), "change", e => {
    const v = parseInt(e.target.value, 10);
    if (v >= 1) { ridgeInterv = v; render(); }
  });

  const gc = document.getElementById("grid-canvas");
  on(gc, "mousemove", e => {
    const rect = gc.getBoundingClientRect();
    gc.style.cursor = nearestGuide(e.clientX - rect.left) !== null ? "pointer" : "crosshair";
  });
  on(gc, "click", e => {
    const rect    = gc.getBoundingClientRect();
    const canvasX = e.clientX - rect.left;
    const canvasY = e.clientY - rect.top;
    const sn = nearestGuide(canvasX);
    if (sn !== null) { showPopup(sn, e.clientX, e.clientY); return; }
    hidePopup();
    if (canvasX < ROW_LABEL_W) return;
    setRow(ridgeNum(Math.floor(canvasY / cellPx)), false);
  });

  on(document, "click", e => {
    const guidePopup = document.getElementById("guide-popup");
    if (!guidePopup.contains(e.target) && e.target !== gc) hidePopup();
  });

  on(document.getElementById("scroll-wrap"), "wheel", e => {
    if (!e.ctrlKey && !e.metaKey) return;
    e.preventDefault();
    setZoom(cellPx + (e.deltaY < 0 ? 1 : -1));
  }, { passive: false });
}

// ── Page interface (registered with PageRegistry) ─────────────────────────────
PageRegistry.register("pearl-earring", {
  id:     "pearl-earring",
  title:  "Girl with a Pearl Earring",
  status: "Completed",

  mount(toolbarMount, bodyMount, shellAPI) {
    _shellAPI = shellAPI;

    toolbarMount.innerHTML = TOOLBAR_HTML;
    bodyMount.innerHTML    = BODY_HTML;

    colHeaderCanvas = document.getElementById("col-header");
    chCtx           = colHeaderCanvas.getContext("2d");
    gridCanvas      = document.getElementById("grid-canvas");
    gCtx            = gridCanvas.getContext("2d");

    document.getElementById("chart-title").textContent = PATTERN.title;
    document.getElementById("goto-input").min = MIN_RIDGE;
    document.getElementById("goto-input").max = MAX_RIDGE;
    document.getElementById("zoom-slider").value = cellPx;

    loadStitchGuide();
    initGuidePopup();

    const saved = loadState();
    if (saved) {
      activeRidge    = Math.max(MIN_RIDGE, Math.min(MAX_RIDGE, saved.ridge  || 1));
      activeStitch   = Math.max(1,         Math.min(NCOLS,     saved.stitch || 1));
      isRightSideRow = !!saved.isRightSide;
    }

    setupEvents();
    setRow(activeRidge, isRightSideRow);
    scrollToActiveStitch();

    shellAPI.setStatus(`${PATTERN.title} — ${MAX_RIDGE} ridges × ${NCOLS} stitches`);
    shellAPI.updateHistBadge();
  },

  unmount() {
    removeAllListeners();
    clearTimeout(histTimer);
    if (pipWindow && !pipWindow.closed) {
      pipWindow.close();
      pipWindow = null; pipCanvas = null; pipCtx = null;
    }
    closeFallbackPip();
    hidePopup();
    _shellAPI = null;
    colHeaderCanvas = null; chCtx = null;
    gridCanvas = null; gCtx = null;
  },

  togglePip() { openPip(); },

  handleKey(e) {
    if (e.key === "Escape") { hidePopup(); return; }
    switch (e.key) {
      case "ArrowUp":   case "k": e.preventDefault(); setRow(activeRidge + 1); break;
      case "ArrowDown": case "j": e.preventDefault(); setRow(activeRidge - 1); break;
      case "Home":     e.preventDefault(); setRow(MIN_RIDGE); break;
      case "End":      e.preventDefault(); setRow(MAX_RIDGE); break;
      case "PageUp":   e.preventDefault(); setRow(activeRidge + ridgeInterv); break;
      case "PageDown": e.preventDefault(); setRow(activeRidge - ridgeInterv); break;
      case "ArrowRight": case " ": e.preventDefault(); setStitch(activeStitch + 10); break;
      case "ArrowLeft":            e.preventDefault(); setStitch(activeStitch - 10); break;
      case "Enter":
        e.preventDefault();
        if (isRightSideRow) { setRow(activeRidge, false); setStitch(STITCH_AT_COL0); }
        else                { setRow(activeRidge + 1, true); }
        break;
      case "+": case "=": setZoom(cellPx + 1); break;
      case "-": case "_": setZoom(cellPx - 1); break;
    }
  },

  // History interface for shell.js
  getHistEntries() { return loadHistory(); },
  deleteHistEntry(idx) {
    const h = loadHistory(); h.splice(idx, 1); saveHistory(h);
    lastHistKey = null;
  },
  clearHistory() { saveHistory([]); lastHistKey = null; },
  navigateToHistEntry(entry) {
    setRow(entry.ridge, !!entry.isRightSide);
    if (entry.stitch != null) setStitch(entry.stitch);
  },
  formatHistEntry(entry) {
    const isRS      = !!entry.isRightSide;
    const isCurrent = entry.ridge === activeRidge && isRS === isRightSideRow;
    const stLabel   = entry.stitch != null ? ` · St.${entry.stitch}` : "";
    return {
      label:      `Ridge ${entry.ridge}${stLabel}`,
      labelClass: isRS ? "rs" : "",
      isCurrent,
    };
  },
  getCurrentPos() {
    const rowType = isRightSideRow ? "Right Side Row" : "Wrong Side Row";
    const pct     = Math.round((activeRidge / MAX_RIDGE) * 100);
    return {
      label: `Ridge ${activeRidge} · St.${activeStitch}`,
      sub:   `${rowType}  ·  ${pct}% through`,
    };
  },
});

})();
